apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: ocp-cloud
rendezvousIP: 10.10.0.201
hosts:
  - hostname: master01.ocp.cloud.lab
    role: master
    interfaces:
      - name: ens18
        macAddress: BC:24:11:0A:05:09
    networkConfig:
      interfaces:
        - name: ens18
          type: ethernet
          state: up
          mac-address: BC:24:11:0A:05:09
          ipv4:
            enabled: true
            address:
              - ip: 10.10.0.201
                prefix-length: 24 
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.10.0.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.10.0.1
            next-hop-interface: ens19
            table-id: 254
  - hostname: master02.ocp.cloud.lab
    role: master
    interfaces:
      - name: ens18
        macAddress: BC:24:11:F7:01:ED
    networkConfig:
      interfaces:
        - name: ens18
          type: ethernet
          state: up
          mac-address: BC:24:11:F7:01:ED
          ipv4:
            enabled: true
            address:
              - ip: 10.10.0.202
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.10.0.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.10.0.1
            next-hop-interface: ens19
            table-id: 254
  - hostname: master03.ocp.cloud.lab
    role: master
    interfaces:
      - name: ens18
        macAddress: BC:24:11:1A:73:30
    networkConfig:
      interfaces:
        - name: ens18
          type: ethernet
          state: up
          mac-address: BC:24:11:1A:73:30
          ipv4:
            enabled: true
            address:
              - ip: 10.10.0.203
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.10.0.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.10.0.1
            next-hop-interface: ens19
            table-id: 254
  - hostname: worker01.ocp.cloud.lab
    role: worker
    interfaces:
      - name: ens18
        macAddress: BC:24:11:FC:2C:A8
    networkConfig:
      interfaces:
        - name: ens18
          type: ethernet
          state: up
          mac-address: BC:24:11:FC:2C:A8
          ipv4:
            enabled: true
            address:
              - ip: 10.10.0.211
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.10.0.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.10.0.1
            next-hop-interface: ens19
            table-id: 254
  - hostname: worker02.ocp.cloud.lab
    role: worker
    interfaces:
      - name: ens18
        macAddress: BC:24:11:F3:59:52
    networkConfig:
      interfaces:
        - name: ens18
          type: ethernet
          state: up
          mac-address: BC:24:11:F3:59:52
          ipv4:
            enabled: true
            address:
              - ip: 10.10.0.212
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.10.0.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.10.0.1
            next-hop-interface: ens19
            table-id: 254
