apiVersion: v1
baseDomain: cloud.lab
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    replicas: 2 # Must be set to 0 for User Provisioned Installation as worker nodes will be manually deployed.
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp # Cluster name
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.10.0.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    hosts:
      - name: master01
        role: master
        bootMACAddress: BC:24:11:44:45:DB
      - name: master02
        role: master
        bootMACAddress: BC:24:11:A4:9D:59
      - name: master03
        role: master
        bootMACAddress: BC:24:11:8D:C5:DB
      - name: worker01
        role: worker
        bootMACAddress: BC:24:11:EC:00:D4
      - name: worker02
        role: worker
        bootMACAddress: BC:24:11:6A:AA:84
    apiVIPs:
    - 10.10.0.1
    ingressVIPs:
    - 10.10.0.2
fips: false
imageDigestSources:
- mirrors:
  - utility:8443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - utility:8443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTg4NDQ2N2VlZmEzNGJiMWEwOGZjNDMwODQyODc3OWI6RVlHR09DUloxNUVCRVMzM0o1N1NaMDNVWDZORzdPWVFSSzFQTTJMM0o0SU1WR01BQ0lWT0xSNzlCWUlTVzdJMw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTg4NDQ2N2VlZmEzNGJiMWEwOGZjNDMwODQyODc3OWI6RVlHR09DUloxNUVCRVMzM0o1N1NaMDNVWDZORzdPWVFSSzFQTTJMM0o0SU1WR01BQ0lWT0xSNzlCWUlTVzdJMw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTI0M2U3NzYxLWZhYjMtNDFjZS1hMWViLWJiNWFmMmYwMTQyNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXhaVGhpWkRobFpXVXlZelEwWm1Jd09EaGxNMlF6WkRRd1lqZ3pPVGN3TUNKOS5TTXgxX2hzNkUyOEIwQ3BlQ0pITTAwWlhTa3pCZm5ZdzFYUVo0T1FyVkExVlhRREpmTk9pSkNZVjdfeTNrYUxEOUF3WXRCNHRLWklMSkRZOTBiWi0tY3ZqdmZfZmVQeEpidXgtbUNOOVE3S0Z1b2RtcTUtTzN4Q2RUVlktMkZVNEhkZElQTk9qQlp1OXZsUDJKdUtiZUdYZklhS1g5R2FRWV8zRWlfVWhNdkNva2RkM2JqN1lsVGhvZlUtLTR0TGNoT29wWm1nLXlxT3BtSUNNaWJtUmI4ZU9HcERNN3oweXdBaDJuYWw1b0JGeVVJZ2syQXZLTFBjX0hQVDJwSDNRTS1IcGpqc3hSRDYxZGhuSmsyWHNKclZEUENPM0o5MkNIX0Qtc1VVd1RFVnpNRWR5WlFrQlZyUi1YS1FlUjE0YjNjbFJCQnZtVnJxM3k3ZENzMFVuZHJJbk5odUgtVXN0Zmd6MFB4WFpuckV2WVVLM1ZFQlBvVjk4NS1BREJ1dmJHOFF1TW1zcjVOR1huOUprb3A3bDhfRFFiN3lmcXpCYWxfVzZpWUV5VDRZSFJzcF8xMHZtN0ppU1lOZ2Z3NXZzOGptRy1OZHZOSUt2TFBlMW4tYVh2VDlNd3h1ZmlHdVBkTm8wcU5hcFdxWENRVmhMWXdMdEVZanVraHd2ckpzS2ZqTkE1dnI1d3l1aV9JajV6aVdUanktRmN6X3NHdDR2anIwSDBCc0p3MTgyalFoMnE3TFBRa0daMGg5dEFOcTkweUViSUFjbHJQSFo5Y19kSWt4UVM1T2hheXlGRjRIbkduZEstSXAzSTFnM1g1empQYk1KUkNqR190LVhVNzI5cUtfSk9yd0NhcXBwWUgtQ2NWMjZIZVV3d2VUOHJoOGp5Yi1kSUR2X3Vfbw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTI0M2U3NzYxLWZhYjMtNDFjZS1hMWViLWJiNWFmMmYwMTQyNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXhaVGhpWkRobFpXVXlZelEwWm1Jd09EaGxNMlF6WkRRd1lqZ3pPVGN3TUNKOS5TTXgxX2hzNkUyOEIwQ3BlQ0pITTAwWlhTa3pCZm5ZdzFYUVo0T1FyVkExVlhRREpmTk9pSkNZVjdfeTNrYUxEOUF3WXRCNHRLWklMSkRZOTBiWi0tY3ZqdmZfZmVQeEpidXgtbUNOOVE3S0Z1b2RtcTUtTzN4Q2RUVlktMkZVNEhkZElQTk9qQlp1OXZsUDJKdUtiZUdYZklhS1g5R2FRWV8zRWlfVWhNdkNva2RkM2JqN1lsVGhvZlUtLTR0TGNoT29wWm1nLXlxT3BtSUNNaWJtUmI4ZU9HcERNN3oweXdBaDJuYWw1b0JGeVVJZ2syQXZLTFBjX0hQVDJwSDNRTS1IcGpqc3hSRDYxZGhuSmsyWHNKclZEUENPM0o5MkNIX0Qtc1VVd1RFVnpNRWR5WlFrQlZyUi1YS1FlUjE0YjNjbFJCQnZtVnJxM3k3ZENzMFVuZHJJbk5odUgtVXN0Zmd6MFB4WFpuckV2WVVLM1ZFQlBvVjk4NS1BREJ1dmJHOFF1TW1zcjVOR1huOUprb3A3bDhfRFFiN3lmcXpCYWxfVzZpWUV5VDRZSFJzcF8xMHZtN0ppU1lOZ2Z3NXZzOGptRy1OZHZOSUt2TFBlMW4tYVh2VDlNd3h1ZmlHdVBkTm8wcU5hcFdxWENRVmhMWXdMdEVZanVraHd2ckpzS2ZqTkE1dnI1d3l1aV9JajV6aVdUanktRmN6X3NHdDR2anIwSDBCc0p3MTgyalFoMnE3TFBRa0daMGg5dEFOcTkweUViSUFjbHJQSFo5Y19kSWt4UVM1T2hheXlGRjRIbkduZEstSXAzSTFnM1g1empQYk1KUkNqR190LVhVNzI5cUtfSk9yd0NhcXBwWUgtQ2NWMjZIZVV3d2VUOHJoOGp5Yi1kSUR2X3Vfbw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"utility:8443":{"auth":"aW5pdDpiOWxPbk5aM1RmVTRYUTEyeWc1SnNkcjdxYXQ4MDZQcA==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"}}}'
sshKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCa5oXw7mm1tUYkCFhbD72XnpZyMU9LaAeLZ0OWCUFP0eADxpx4viNgPB9Ol1wHkJ5e0d+5tvd7ppZvpruedtB2q3MeShuFRSOatK+gU5ixvghF0opTO5S1Q3liholfmuw1UDbmJvcLgG/6iNbrdvPw8v6exuIUsEjLIbKfGAUfuIdRTzreIZ5hQZ92hH1lRVCXxzr3DUsGiuVBSYlOKKKbzPQ5imC3HndCRdSUOhoMCNLuAJij/2YXBhbNxN+BzntL1p+XOEIcK69nDrLAN4JZXTP7hIDjysDJ0j6CyoLGEx9xYCww9xlhaiGuDT8CnQh0OynEONc/F49L96plnT8XNTlfV8BPdSzNG+taIJOiQv3RJfCIrW0MgAIZR7XXnisH4QVHmMwge5FZBT9vPhm39fl6QW3wIct/W2hljja5oSHu1BrFBu0ZH3AtsmCg0Zp+8AL08hctpvdgaU9BGWE7MpNx5qsb6JcSWkMoTyrgVz7OrsYb5wm/DvB5rsNloFE= root@utility"
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIDgTCCAmmgAwIBAgIUGSZdHsO9Mq4HakILWyhV9hO9XnEwDQYJKoZIhvcNAQEL
  BQAwYTELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y 
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xEDAOBgNVBAMMB3V0
  aWxpdHkwHhcNMjQwOTI0MTg0NDIxWhcNMjUwOTE1MTg0NDIxWjAaMRgwFgYDVQQD
  DA9xdWF5LWVudGVycHJpc2UwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
  AQCigNsqep6Bbk02rQLDL543vdcjxICwbAjfDOs/vF0VA1sn0u/7ZXE/mbAV+fCd
  0WU+oFwQvtJu/+SPQD8vgsL1mV7LS2f9aJsG9wgS08hpXzROakUCOKupJzuK3VfE
  a0X7//xIO42rc2xtdhx/Nxhk1mQHMlChYEL1YI+iU3nyxi837pDxzW3YKEQWjla1
  uhUIB4U2XI7R9z7umj6xuqpZVAdeoN06BW7pVxCz3nBm7gb8l2YmJe+lUE6LY59z
  /uhwrqYXAlaaKYpuUDBVB8NFK1b1cbCkTK5DiLyDePsyQB56uxxZ1E0tuhyUiuj/
  dTBObsI5BWg72VXK8IS4o6rZAgMBAAGjeDB2MAsGA1UdDwQEAwIC5DATBgNVHSUE
  DDAKBggrBgEFBQcDATASBgNVHREECzAJggd1dGlsaXR5MB0GA1UdDgQWBBRSHqTl
  R1cYw0QngTxnmjf1x3jYPzAfBgNVHSMEGDAWgBQY4oX93kGyT25h33aEzi21zImm
  vzANBgkqhkiG9w0BAQsFAAOCAQEAjVU6Lpe2W8mbZo6SFFH8HCtuWh4iTBOqHDOW
  5ZxfT0RpFfrQ6vLzgt9s7k3q1EDpjEanGAMUV588yg1v0m9XBQPSuYqbZOyjGXsX
  wizaUZQI+bRVGgGyxn+qnMr5HUMa7r2ihkzNdsiaFsm1A2ul6FLFZ/neOpM+saHj
  47Z572lkcL53GvMgLAdSp4ysArNpQHqbQZ+XzCm7h1rF/sUcppHmgQ0vWfVlgZb2
  VCzcLGpPv/HQ7EHloHMsuhb0R1H0GfjGWVjiRhT0uUwc/nwnuKoh0Yt4C9nweTQb
  GG3XOacsmOnM5U369kvSOh/pM5zmpKgJW0Mejh/IC4+oUZdViw==
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIDuzCCAqOgAwIBAgIUaYTQa+f+EiI0A/56LZW7rVVsWVUwDQYJKoZIhvcNAQEL
  BQAwYTELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xEDAOBgNVBAMMB3V0
  aWxpdHkwHhcNMjQwOTI0MTg0NDE3WhcNMjcwNzE1MTg0NDE3WjBhMQswCQYDVQQG
  EwJVUzELMAkGA1UECAwCVkExETAPBgNVBAcMCE5ldyBZb3JrMQ0wCwYDVQQKDARR
  dWF5MREwDwYDVQQLDAhEaXZpc2lvbjEQMA4GA1UEAwwHdXRpbGl0eTCCASIwDQYJ
  KoZIhvcNAQEBBQADggEPADCCAQoCggEBALY7+V4oGJsQf5NE3dc6V+sL3kuOHgyR
  Yn4jYvKU85Zi+B9LUyT1q4B0zZr8b5g1xJaCBqib2N0LEgL/5Cb7k+l9L0HAaCnY
  graFsu9v+h/xBFRfRC9ZRtnjB6sSatmgD+Ok1xsaRjXqcwmnX+ktA6YWeC/LPcz+
  Q0MD0syrwcpo3GoTdV9FaNUe6hjVTlVUUa7r9mknsWqvamwF98eGXIYGKIYeMlT+
  q5Xtgc6b5Qp9ZOpEiNM9otWzg6THXhnlYibkBLBcpgPZgXyFwoReBhngGxQAZBYn
  PklwepdokdDSJUddXxyzJduNIjOV6oVEoZfbHA1iPkQVuNTEn7hle9ECAwEAAaNr
  MGkwCwYDVR0PBAQDAgLkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMBIGA1UdEQQLMAmC
  B3V0aWxpdHkwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUGOKF/d5Bsk9u
  Yd92hM4ttcyJpr8wDQYJKoZIhvcNAQELBQADggEBADOOTh5Ld1D7NrmVdTKS3vLU
  16MdlaMfdvMVImx6MlRgbRju/72z3ef0zgF+SxDWiZeVfikBNTFPz4S+SG38qoqj
  2TnxhgHedmTGu58wdzcnAh8OZ+gKoCgsFq/lnX4pLPNBasuuAqOOQ8jbbrA9FvVo
  tnOzZ4tsYDcdSkugY307czVFnDECmS3R50hyglY+KgJNHwGmWNdD9W8NvxoMxwfA
  q8yeKBkQn2UtNPTXLA1LwQHcpuZ3HZPMudgiAMMA1JKWmMwKgCw3vR2FoQ2QAMo2
  6zlizMImCO+KIguBG7rlpNK4B698sRStHBa/WGee5M1q0rcM1kM4+TOSSMB5B9Q=
  -----END CERTIFICATE-----