apiVersion: v1
baseDomain: cloud.lab
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    replicas: 2 # Must be set to 0 for User Provisioned Installation as worker nodes will be manually deployed.
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp # Cluster name
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.10.0.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    apiVIPs:
    - 10.10.0.1
    ingressVIPs:
    - 10.10.0.2
fips: false
imageDigestSources:
- mirrors:
  - utility:8443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - utility:8443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTg4NDQ2N2VlZmEzNGJiMWEwOGZjNDMwODQyODc3OWI6RVlHR09DUloxNUVCRVMzM0o1N1NaMDNVWDZORzdPWVFSSzFQTTJMM0o0SU1WR01BQ0lWT0xSNzlCWUlTVzdJMw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTg4NDQ2N2VlZmEzNGJiMWEwOGZjNDMwODQyODc3OWI6RVlHR09DUloxNUVCRVMzM0o1N1NaMDNVWDZORzdPWVFSSzFQTTJMM0o0SU1WR01BQ0lWT0xSNzlCWUlTVzdJMw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTI0M2U3NzYxLWZhYjMtNDFjZS1hMWViLWJiNWFmMmYwMTQyNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXhaVGhpWkRobFpXVXlZelEwWm1Jd09EaGxNMlF6WkRRd1lqZ3pPVGN3TUNKOS5TTXgxX2hzNkUyOEIwQ3BlQ0pITTAwWlhTa3pCZm5ZdzFYUVo0T1FyVkExVlhRREpmTk9pSkNZVjdfeTNrYUxEOUF3WXRCNHRLWklMSkRZOTBiWi0tY3ZqdmZfZmVQeEpidXgtbUNOOVE3S0Z1b2RtcTUtTzN4Q2RUVlktMkZVNEhkZElQTk9qQlp1OXZsUDJKdUtiZUdYZklhS1g5R2FRWV8zRWlfVWhNdkNva2RkM2JqN1lsVGhvZlUtLTR0TGNoT29wWm1nLXlxT3BtSUNNaWJtUmI4ZU9HcERNN3oweXdBaDJuYWw1b0JGeVVJZ2syQXZLTFBjX0hQVDJwSDNRTS1IcGpqc3hSRDYxZGhuSmsyWHNKclZEUENPM0o5MkNIX0Qtc1VVd1RFVnpNRWR5WlFrQlZyUi1YS1FlUjE0YjNjbFJCQnZtVnJxM3k3ZENzMFVuZHJJbk5odUgtVXN0Zmd6MFB4WFpuckV2WVVLM1ZFQlBvVjk4NS1BREJ1dmJHOFF1TW1zcjVOR1huOUprb3A3bDhfRFFiN3lmcXpCYWxfVzZpWUV5VDRZSFJzcF8xMHZtN0ppU1lOZ2Z3NXZzOGptRy1OZHZOSUt2TFBlMW4tYVh2VDlNd3h1ZmlHdVBkTm8wcU5hcFdxWENRVmhMWXdMdEVZanVraHd2ckpzS2ZqTkE1dnI1d3l1aV9JajV6aVdUanktRmN6X3NHdDR2anIwSDBCc0p3MTgyalFoMnE3TFBRa0daMGg5dEFOcTkweUViSUFjbHJQSFo5Y19kSWt4UVM1T2hheXlGRjRIbkduZEstSXAzSTFnM1g1empQYk1KUkNqR190LVhVNzI5cUtfSk9yd0NhcXBwWUgtQ2NWMjZIZVV3d2VUOHJoOGp5Yi1kSUR2X3Vfbw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTI0M2U3NzYxLWZhYjMtNDFjZS1hMWViLWJiNWFmMmYwMTQyNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXhaVGhpWkRobFpXVXlZelEwWm1Jd09EaGxNMlF6WkRRd1lqZ3pPVGN3TUNKOS5TTXgxX2hzNkUyOEIwQ3BlQ0pITTAwWlhTa3pCZm5ZdzFYUVo0T1FyVkExVlhRREpmTk9pSkNZVjdfeTNrYUxEOUF3WXRCNHRLWklMSkRZOTBiWi0tY3ZqdmZfZmVQeEpidXgtbUNOOVE3S0Z1b2RtcTUtTzN4Q2RUVlktMkZVNEhkZElQTk9qQlp1OXZsUDJKdUtiZUdYZklhS1g5R2FRWV8zRWlfVWhNdkNva2RkM2JqN1lsVGhvZlUtLTR0TGNoT29wWm1nLXlxT3BtSUNNaWJtUmI4ZU9HcERNN3oweXdBaDJuYWw1b0JGeVVJZ2syQXZLTFBjX0hQVDJwSDNRTS1IcGpqc3hSRDYxZGhuSmsyWHNKclZEUENPM0o5MkNIX0Qtc1VVd1RFVnpNRWR5WlFrQlZyUi1YS1FlUjE0YjNjbFJCQnZtVnJxM3k3ZENzMFVuZHJJbk5odUgtVXN0Zmd6MFB4WFpuckV2WVVLM1ZFQlBvVjk4NS1BREJ1dmJHOFF1TW1zcjVOR1huOUprb3A3bDhfRFFiN3lmcXpCYWxfVzZpWUV5VDRZSFJzcF8xMHZtN0ppU1lOZ2Z3NXZzOGptRy1OZHZOSUt2TFBlMW4tYVh2VDlNd3h1ZmlHdVBkTm8wcU5hcFdxWENRVmhMWXdMdEVZanVraHd2ckpzS2ZqTkE1dnI1d3l1aV9JajV6aVdUanktRmN6X3NHdDR2anIwSDBCc0p3MTgyalFoMnE3TFBRa0daMGg5dEFOcTkweUViSUFjbHJQSFo5Y19kSWt4UVM1T2hheXlGRjRIbkduZEstSXAzSTFnM1g1empQYk1KUkNqR190LVhVNzI5cUtfSk9yd0NhcXBwWUgtQ2NWMjZIZVV3d2VUOHJoOGp5Yi1kSUR2X3Vfbw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"utility:8443":{"auth":"aW5pdDpiOWxPbk5aM1RmVTRYUTEyeWc1SnNkcjdxYXQ4MDZQcA==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"}}}'
sshKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCa5oXw7mm1tUYkCFhbD72XnpZyMU9LaAeLZ0OWCUFP0eADxpx4viNgPB9Ol1wHkJ5e0d+5tvd7ppZvpruedtB2q3MeShuFRSOatK+gU5ixvghF0opTO5S1Q3liholfmuw1UDbmJvcLgG/6iNbrdvPw8v6exuIUsEjLIbKfGAUfuIdRTzreIZ5hQZ92hH1lRVCXxzr3DUsGiuVBSYlOKKKbzPQ5imC3HndCRdSUOhoMCNLuAJij/2YXBhbNxN+BzntL1p+XOEIcK69nDrLAN4JZXTP7hIDjysDJ0j6CyoLGEx9xYCww9xlhaiGuDT8CnQh0OynEONc/F49L96plnT8XNTlfV8BPdSzNG+taIJOiQv3RJfCIrW0MgAIZR7XXnisH4QVHmMwge5FZBT9vPhm39fl6QW3wIct/W2hljja5oSHu1BrFBu0ZH3AtsmCg0Zp+8AL08hctpvdgaU9BGWE7MpNx5qsb6JcSWkMoTyrgVz7OrsYb5wm/DvB5rsNloFE= root@utility"
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIDgTCCAmmgAwIBAgIUUwNwAAVUtb3uB4ClcYdgUsjVG6cwDQYJKoZIhvcNAQEL
  BQAwYTELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xEDAOBgNVBAMMB3V0
  aWxpdHkwHhcNMjQwOTI3MTcyNjQ0WhcNMjUwOTE4MTcyNjQ0WjAaMRgwFgYDVQQD
  DA9xdWF5LWVudGVycHJpc2UwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
  AQCZDH1T4lVbYaiZUEnhZfzw/a66X3iVF0RblxypydilgFwpOQ2JcBM1LiktCE25
  EGaQ4MtUVr0PGZcbNAAwAdw+K+OkhBw2yxww63+jXJ20LdcrPaP7dzDuKBh6s8gk
  cAJjl4NZErnMSIW+VKpskfoPMGCGmUis0vBaCGSKhxI7d9wABbiVJXGvCPXlBst8
  AyJYU5K3SJogdeYsg9V4QD+8zeaFXI78yTEmp4GJZ0HnKbuKpV49tjto3+wX72L3
  6f46sqegWj2Y5s6LRTtgiX897lXqpXNENnvljI5GQCMkg7oxgdYGKc14xVaQSw+4
  pY95VyLWPFJ/Z3V5IggZW4NxAgMBAAGjeDB2MAsGA1UdDwQEAwIC5DATBgNVHSUE
  DDAKBggrBgEFBQcDATASBgNVHREECzAJggd1dGlsaXR5MB0GA1UdDgQWBBTT6Yf0
  Gid2e7IfADXgsTpzYUyaDzAfBgNVHSMEGDAWgBSeKain8neMcl02QtHDwd0zWv3c
  6DANBgkqhkiG9w0BAQsFAAOCAQEAN1LicH/lBCOhfVe+gsghGDbUZNo85biR2K7A
  yoN+mML+d+gHIAMOIjjkiRiBo8D/CpSEhlLkc4iZcxhZVUHjVWPAk+QVrQ7u3GBl
  SKpQuzJcQWv6p/HhYgbnDfAQhEatm3l1Ec76TlqQJD2AoPPV53oNk1GciJTPTSId
  Ix4ITB6kxPnHJdqVtDe1Wxnbt4lH9QDhDREf0hLzZEG4w3vpKyd5bTsFhpdJq5M2
  BoOztpk8ftcDeiTP0xA4ygo/Lnp7lWkSLGA76K1fUBXAy025OVOJAyfz34s8SRXU
  UKH9l/zkMYspHH5wSx2Yfo+u61kChvQVXtATQVtOVe1aDv+2Og==
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIDuzCCAqOgAwIBAgIUXtQhn2+SKwhqc12xSazfr0b0dcgwDQYJKoZIhvcNAQEL
  BQAwYTELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xEDAOBgNVBAMMB3V0
  aWxpdHkwHhcNMjQwOTI3MTcyNjM5WhcNMjcwNzE4MTcyNjM5WjBhMQswCQYDVQQG
  EwJVUzELMAkGA1UECAwCVkExETAPBgNVBAcMCE5ldyBZb3JrMQ0wCwYDVQQKDARR
  dWF5MREwDwYDVQQLDAhEaXZpc2lvbjEQMA4GA1UEAwwHdXRpbGl0eTCCASIwDQYJ
  KoZIhvcNAQEBBQADggEPADCCAQoCggEBAOEhuvtOJk+1r0gZDi0OtPqs19ZNWOzl
  vdFNKJ34/4YI8sK5BWHG5/wxwy4bCRscNrmsNX2V2HmPC2op6zCdeydNg1YweWtn
  m60iTZ/JPZiWAZhpPsy4BVZVUe4gnaoTGnaG5YPaPKOIaDtxE8GsWQD5F0Qg3uFe
  oLGubQPFtR1ZOmqXG0DfT9dTo3xdWUy3oB/F0iRTZK+aQvODz37MW6L7YZupI1CX
  Bf+0l1j4OqMHchcPOe6/pMXJKz3Mm9Fy4Ftt5ZcKwaMUNMiU+8B2LVCqAdp4BAeu
  wettrwB7aE+fVL6iOebTV7hEncLC+MNyfrnpTvl6KU7oOatOPwJiCQ8CAwEAAaNr
  MGkwCwYDVR0PBAQDAgLkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMBIGA1UdEQQLMAmC
  B3V0aWxpdHkwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUnimop/J3jHJd
  NkLRw8HdM1r93OgwDQYJKoZIhvcNAQELBQADggEBADubkkFKGXZolBZzMXeUfVEy
  udMk3e0OibWuaLnlKuUCIZCh98GeCnoc3fr/uakerC1wu2M14nu4nEBZdk9OXEOF
  Xb6J6stcyEl1YfO6wGU/GfmbTw+14hglfP9c92p2YqaxLrOTa5mXThJ81lHymsIb
  q6dRtR+zGG5JD9Xkx/YsqNYT78n7/7NQtRSSVoTFjm8DbNeW3UhG7+gIl14a50z2
  Rzp9f9PFj2lNXykN80dIH2hOrDjesj6b7Hp1aZe34++S9eaX19M7ik01CDi6cqcU
  ur7WTcZAOJ0ZuuFbp3L0UKxJ0TGMbYcsr9DVlbQp79eNg4bC41FBMMYQZwNs4eo=
  -----END CERTIFICATE-----