apiVersion: v1
baseDomain: cloud.lab
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    replicas: 0 # Must be set to 0 for User Provisioned Installation as worker nodes will be manually deployed.
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp # Cluster name
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
imageContentSources:
- mirrors:
  - utility.cloud.lab:8443/openshift/release-images
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - utility.cloud.lab:8443/openshift/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTg4NDQ2N2VlZmEzNGJiMWEwOGZjNDMwODQyODc3OWI6RVlHR09DUloxNUVCRVMzM0o1N1NaMDNVWDZORzdPWVFSSzFQTTJMM0o0SU1WR01BQ0lWT0xSNzlCWUlTVzdJMw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTg4NDQ2N2VlZmEzNGJiMWEwOGZjNDMwODQyODc3OWI6RVlHR09DUloxNUVCRVMzM0o1N1NaMDNVWDZORzdPWVFSSzFQTTJMM0o0SU1WR01BQ0lWT0xSNzlCWUlTVzdJMw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTI0M2U3NzYxLWZhYjMtNDFjZS1hMWViLWJiNWFmMmYwMTQyNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXhaVGhpWkRobFpXVXlZelEwWm1Jd09EaGxNMlF6WkRRd1lqZ3pPVGN3TUNKOS5TTXgxX2hzNkUyOEIwQ3BlQ0pITTAwWlhTa3pCZm5ZdzFYUVo0T1FyVkExVlhRREpmTk9pSkNZVjdfeTNrYUxEOUF3WXRCNHRLWklMSkRZOTBiWi0tY3ZqdmZfZmVQeEpidXgtbUNOOVE3S0Z1b2RtcTUtTzN4Q2RUVlktMkZVNEhkZElQTk9qQlp1OXZsUDJKdUtiZUdYZklhS1g5R2FRWV8zRWlfVWhNdkNva2RkM2JqN1lsVGhvZlUtLTR0TGNoT29wWm1nLXlxT3BtSUNNaWJtUmI4ZU9HcERNN3oweXdBaDJuYWw1b0JGeVVJZ2syQXZLTFBjX0hQVDJwSDNRTS1IcGpqc3hSRDYxZGhuSmsyWHNKclZEUENPM0o5MkNIX0Qtc1VVd1RFVnpNRWR5WlFrQlZyUi1YS1FlUjE0YjNjbFJCQnZtVnJxM3k3ZENzMFVuZHJJbk5odUgtVXN0Zmd6MFB4WFpuckV2WVVLM1ZFQlBvVjk4NS1BREJ1dmJHOFF1TW1zcjVOR1huOUprb3A3bDhfRFFiN3lmcXpCYWxfVzZpWUV5VDRZSFJzcF8xMHZtN0ppU1lOZ2Z3NXZzOGptRy1OZHZOSUt2TFBlMW4tYVh2VDlNd3h1ZmlHdVBkTm8wcU5hcFdxWENRVmhMWXdMdEVZanVraHd2ckpzS2ZqTkE1dnI1d3l1aV9JajV6aVdUanktRmN6X3NHdDR2anIwSDBCc0p3MTgyalFoMnE3TFBRa0daMGg5dEFOcTkweUViSUFjbHJQSFo5Y19kSWt4UVM1T2hheXlGRjRIbkduZEstSXAzSTFnM1g1empQYk1KUkNqR190LVhVNzI5cUtfSk9yd0NhcXBwWUgtQ2NWMjZIZVV3d2VUOHJoOGp5Yi1kSUR2X3Vfbw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTI0M2U3NzYxLWZhYjMtNDFjZS1hMWViLWJiNWFmMmYwMTQyNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXhaVGhpWkRobFpXVXlZelEwWm1Jd09EaGxNMlF6WkRRd1lqZ3pPVGN3TUNKOS5TTXgxX2hzNkUyOEIwQ3BlQ0pITTAwWlhTa3pCZm5ZdzFYUVo0T1FyVkExVlhRREpmTk9pSkNZVjdfeTNrYUxEOUF3WXRCNHRLWklMSkRZOTBiWi0tY3ZqdmZfZmVQeEpidXgtbUNOOVE3S0Z1b2RtcTUtTzN4Q2RUVlktMkZVNEhkZElQTk9qQlp1OXZsUDJKdUtiZUdYZklhS1g5R2FRWV8zRWlfVWhNdkNva2RkM2JqN1lsVGhvZlUtLTR0TGNoT29wWm1nLXlxT3BtSUNNaWJtUmI4ZU9HcERNN3oweXdBaDJuYWw1b0JGeVVJZ2syQXZLTFBjX0hQVDJwSDNRTS1IcGpqc3hSRDYxZGhuSmsyWHNKclZEUENPM0o5MkNIX0Qtc1VVd1RFVnpNRWR5WlFrQlZyUi1YS1FlUjE0YjNjbFJCQnZtVnJxM3k3ZENzMFVuZHJJbk5odUgtVXN0Zmd6MFB4WFpuckV2WVVLM1ZFQlBvVjk4NS1BREJ1dmJHOFF1TW1zcjVOR1huOUprb3A3bDhfRFFiN3lmcXpCYWxfVzZpWUV5VDRZSFJzcF8xMHZtN0ppU1lOZ2Z3NXZzOGptRy1OZHZOSUt2TFBlMW4tYVh2VDlNd3h1ZmlHdVBkTm8wcU5hcFdxWENRVmhMWXdMdEVZanVraHd2ckpzS2ZqTkE1dnI1d3l1aV9JajV6aVdUanktRmN6X3NHdDR2anIwSDBCc0p3MTgyalFoMnE3TFBRa0daMGg5dEFOcTkweUViSUFjbHJQSFo5Y19kSWt4UVM1T2hheXlGRjRIbkduZEstSXAzSTFnM1g1empQYk1KUkNqR190LVhVNzI5cUtfSk9yd0NhcXBwWUgtQ2NWMjZIZVV3d2VUOHJoOGp5Yi1kSUR2X3Vfbw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"utility.cloud.lab:8443":{"auth":"aW5pdDpFRzJrdTFyVDQ2YTc5TjVDMFlqc0hwejNBcThJaXdXWg==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"}}}'
sshKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDiZK/Vg5LFL+ntPLxdNgBBpjLUYl1H7wzjdAlPT3au00I0WRyKmNTicr1pbo6+6deHFiGO7SsoWFkI2eVyJ+bncl0Ew2aUPE9PRIAGdWMklFI3yk2AHY5T89QlOGa67N3ZaxVjzP4qoXglcfehzuYK7Z2BMmUbYsMFch+3Oa7NrMgSFwNAIE5kkIzio4tEXdRSaANUjGdJSry4gOMo+82DyWoJzNPnRz/6SPuhLtalqE51rdOeUQ93cUgRzxSMFfmZjTZw6BYXvWhGHoQ//4j2fAhnJfdKmdasgDi6NwUYbDihG8ODjWinmyxHR8wGazbqZZP1i707ljF5Oale80sPluMxPQXS81tSbnfsr4aU334bZ0V6wC/XQxW1PRvUZXXjjQIx6xM6T2BRAxfG+MT8wf84ZN2hdg6Pm7p6SmOjY9glC+6vQZzo32pjgjU/GAtjb8rr19KJIfiDcjOObl/wAuf5xPQ7ZBd+35km8ar+7WBewkDCiGy6KVMRyHBiNdM= root@utility.cloud.lab"
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIDlzCCAn+gAwIBAgIUBqxTKvhGv2+yg4IZjPRSzoLEdLEwDQYJKoZIhvcNAQEL
  BQAwazELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xGjAYBgNVBAMMEXV0
  aWxpdHkuY2xvdWQubGFiMB4XDTI1MDIyNzE1MzkwN1oXDTI2MDIxODE1MzkwN1ow
  GjEYMBYGA1UEAwwPcXVheS1lbnRlcnByaXNlMIIBIjANBgkqhkiG9w0BAQEFAAOC
  AQ8AMIIBCgKCAQEA6jetc9csohyTUNA/KWplK/8Naejxzy85+P3Ko0Wmk5q01ETL
  RfP0cFRXQ27iAZuOXLWsBOvbaLOskX8/gcYwpVTu3ZiXcBFJfOgCPw1cu+0tZPYM
  JarwpxYsIaNXPMm6luFB3RTZ6CS+7Lq+nVc8fCYLiA0Ue+yPGdVFDWuxfh26uqsH
  fjmGQuwSHL93xV5FLw+7p6wb5SRsMvcZ+ZQyJbxoAi0aHrNZI7u1E8jMTnxv+5i4
  R2SNmueFhgoWrrJK39Bu1hNWhcTr1ziR/Ai3/0B4GwT27ZRA1mYvMb3M8NrGRsIY
  wHv+uUpYTqeGAup6BwgHaQWQININzYB7r8K4hQIDAQABo4GDMIGAMAsGA1UdDwQE
  AwIC5DATBgNVHSUEDDAKBggrBgEFBQcDATAcBgNVHREEFTATghF1dGlsaXR5LmNs
  b3VkLmxhYjAdBgNVHQ4EFgQUbzqijP/Ds5Ga0ag/P+2A+/q+VbgwHwYDVR0jBBgw
  FoAU70+ucw9wM5sIhzUxEbxazUY5zr8wDQYJKoZIhvcNAQELBQADggEBALO2rNQ0
  80uqWt/ARvGCHZF8MbXDPfYvdQbw5Ozsn44bV1NXTCo6eubOXSF7XqHICYN7Uh4e
  CKvovziCWsl75dyH+gthbyjSsAd96LQIFteRGdz4uZADKCvElLEwHZLa7oNtpelh
  70iUZ9GJVM5O39t6tG/pEDkHVoi7nM1e+KXHkCNdLTA0QUbGEMNAb851TFgweIDF
  ycQm88uFss8uKUm5bbtq5cSY8gjUPpvoePn4RdyXhdGWU4PuKrUITXXzirYZaFM2
  +7u+UO5xW7K+9MStZzBn54Va59QQFgKjvpDfqzZc83RN6GksO4f3dKzeUnErQCkc
  2UGwowuxCxxxq70=
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIID2TCCAsGgAwIBAgIUPKLUrplI2xxzOfFcfuKyKzPeGxkwDQYJKoZIhvcNAQEL
  BQAwazELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xGjAYBgNVBAMMEXV0
  aWxpdHkuY2xvdWQubGFiMB4XDTI1MDIyNzE1MzkwM1oXDTI3MTIxODE1MzkwM1ow
  azELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9yazEN
  MAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xGjAYBgNVBAMMEXV0aWxp
  dHkuY2xvdWQubGFiMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8a5n
  pc6U8r+18qBoLvODinPoKzaYgZnYrbukkEbYbD/e5bFmG/XLH3yURrFq7AqYeQCM
  Pg5FfAksYvAuheTTzGVkrkyTOCh9LpunkHQzyagIZ7bvyMiEwk64i16s3KiHzfMJ
  ivdq3FaH6Fey9OTUB4WFuMsSHDvU+Wzd7kUhCdD84rbH2dru0Smrk7w8A9DxbQOV
  vAS/LYI0xF+YbHR0RWq7V509BOaVRVx8Skqj2OscTWsoAPRko16g6p3afwK6B0YR
  e/9dzfsASFysuB3IQsDjwDRPFj/UCeg/hO1AzeCbv84El23GSmy87m87ThT8zYjp
  XdO5gyLz5MkWw/ntkwIDAQABo3UwczALBgNVHQ8EBAMCAuQwEwYDVR0lBAwwCgYI
  KwYBBQUHAwEwHAYDVR0RBBUwE4IRdXRpbGl0eS5jbG91ZC5sYWIwEgYDVR0TAQH/
  BAgwBgEB/wIBATAdBgNVHQ4EFgQU70+ucw9wM5sIhzUxEbxazUY5zr8wDQYJKoZI
  hvcNAQELBQADggEBAMWkqZr8ic4xd66GdaxZqhaNkVXR2WCdq8rkkhEZyBlBn1HO
  wJ/zEE/iNhkvri/+dgKSYYpaqSZFQi80H3Im8mrbRMZ6+kEEX5XYNmi9QXmUtm9+
  VaRcWKfi+hP2es3FttSi7/MuVNt/FXi/ktr6btMhjQyo1WfnOtdl70OYYEhh4l6y
  R7W4F2PMLrceKqLKrimXiaI2/iIYgek61vuC3hCWbf3uOKam4Dh61LcNC40xnQ8x
  ItjQV5I2zDQb1FTEF0XnGsWSFoGM5jOZsM876bjOIjq/RgwNfbn4WOQx6pJi7UPY
  FVd2Unfj778X3riQR8hvmtHr0dFTqAlNAm44ahY=
  -----END CERTIFICATE-----