apiVersion: v1
baseDomain: cloud.lab
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    replicas: 0 # Must be set to 0 for User Provisioned Installation as worker nodes will be manually deployed.
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp # Cluster name
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
imageContentSources:
- mirrors:
  - utility.cloud.lab:8443/openshift/release-images
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - utility.cloud.lab:8443/openshift/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTg4NDQ2N2VlZmEzNGJiMWEwOGZjNDMwODQyODc3OWI6RVlHR09DUloxNUVCRVMzM0o1N1NaMDNVWDZORzdPWVFSSzFQTTJMM0o0SU1WR01BQ0lWT0xSNzlCWUlTVzdJMw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTg4NDQ2N2VlZmEzNGJiMWEwOGZjNDMwODQyODc3OWI6RVlHR09DUloxNUVCRVMzM0o1N1NaMDNVWDZORzdPWVFSSzFQTTJMM0o0SU1WR01BQ0lWT0xSNzlCWUlTVzdJMw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTI0M2U3NzYxLWZhYjMtNDFjZS1hMWViLWJiNWFmMmYwMTQyNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXhaVGhpWkRobFpXVXlZelEwWm1Jd09EaGxNMlF6WkRRd1lqZ3pPVGN3TUNKOS5TTXgxX2hzNkUyOEIwQ3BlQ0pITTAwWlhTa3pCZm5ZdzFYUVo0T1FyVkExVlhRREpmTk9pSkNZVjdfeTNrYUxEOUF3WXRCNHRLWklMSkRZOTBiWi0tY3ZqdmZfZmVQeEpidXgtbUNOOVE3S0Z1b2RtcTUtTzN4Q2RUVlktMkZVNEhkZElQTk9qQlp1OXZsUDJKdUtiZUdYZklhS1g5R2FRWV8zRWlfVWhNdkNva2RkM2JqN1lsVGhvZlUtLTR0TGNoT29wWm1nLXlxT3BtSUNNaWJtUmI4ZU9HcERNN3oweXdBaDJuYWw1b0JGeVVJZ2syQXZLTFBjX0hQVDJwSDNRTS1IcGpqc3hSRDYxZGhuSmsyWHNKclZEUENPM0o5MkNIX0Qtc1VVd1RFVnpNRWR5WlFrQlZyUi1YS1FlUjE0YjNjbFJCQnZtVnJxM3k3ZENzMFVuZHJJbk5odUgtVXN0Zmd6MFB4WFpuckV2WVVLM1ZFQlBvVjk4NS1BREJ1dmJHOFF1TW1zcjVOR1huOUprb3A3bDhfRFFiN3lmcXpCYWxfVzZpWUV5VDRZSFJzcF8xMHZtN0ppU1lOZ2Z3NXZzOGptRy1OZHZOSUt2TFBlMW4tYVh2VDlNd3h1ZmlHdVBkTm8wcU5hcFdxWENRVmhMWXdMdEVZanVraHd2ckpzS2ZqTkE1dnI1d3l1aV9JajV6aVdUanktRmN6X3NHdDR2anIwSDBCc0p3MTgyalFoMnE3TFBRa0daMGg5dEFOcTkweUViSUFjbHJQSFo5Y19kSWt4UVM1T2hheXlGRjRIbkduZEstSXAzSTFnM1g1empQYk1KUkNqR190LVhVNzI5cUtfSk9yd0NhcXBwWUgtQ2NWMjZIZVV3d2VUOHJoOGp5Yi1kSUR2X3Vfbw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTI0M2U3NzYxLWZhYjMtNDFjZS1hMWViLWJiNWFmMmYwMTQyNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXhaVGhpWkRobFpXVXlZelEwWm1Jd09EaGxNMlF6WkRRd1lqZ3pPVGN3TUNKOS5TTXgxX2hzNkUyOEIwQ3BlQ0pITTAwWlhTa3pCZm5ZdzFYUVo0T1FyVkExVlhRREpmTk9pSkNZVjdfeTNrYUxEOUF3WXRCNHRLWklMSkRZOTBiWi0tY3ZqdmZfZmVQeEpidXgtbUNOOVE3S0Z1b2RtcTUtTzN4Q2RUVlktMkZVNEhkZElQTk9qQlp1OXZsUDJKdUtiZUdYZklhS1g5R2FRWV8zRWlfVWhNdkNva2RkM2JqN1lsVGhvZlUtLTR0TGNoT29wWm1nLXlxT3BtSUNNaWJtUmI4ZU9HcERNN3oweXdBaDJuYWw1b0JGeVVJZ2syQXZLTFBjX0hQVDJwSDNRTS1IcGpqc3hSRDYxZGhuSmsyWHNKclZEUENPM0o5MkNIX0Qtc1VVd1RFVnpNRWR5WlFrQlZyUi1YS1FlUjE0YjNjbFJCQnZtVnJxM3k3ZENzMFVuZHJJbk5odUgtVXN0Zmd6MFB4WFpuckV2WVVLM1ZFQlBvVjk4NS1BREJ1dmJHOFF1TW1zcjVOR1huOUprb3A3bDhfRFFiN3lmcXpCYWxfVzZpWUV5VDRZSFJzcF8xMHZtN0ppU1lOZ2Z3NXZzOGptRy1OZHZOSUt2TFBlMW4tYVh2VDlNd3h1ZmlHdVBkTm8wcU5hcFdxWENRVmhMWXdMdEVZanVraHd2ckpzS2ZqTkE1dnI1d3l1aV9JajV6aVdUanktRmN6X3NHdDR2anIwSDBCc0p3MTgyalFoMnE3TFBRa0daMGg5dEFOcTkweUViSUFjbHJQSFo5Y19kSWt4UVM1T2hheXlGRjRIbkduZEstSXAzSTFnM1g1empQYk1KUkNqR190LVhVNzI5cUtfSk9yd0NhcXBwWUgtQ2NWMjZIZVV3d2VUOHJoOGp5Yi1kSUR2X3Vfbw==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"},"utility.cloud.lab:8443":{"auth":"aW5pdDozNzA4RWVvNXV0SmFpUjZTajRyQTl5UEtXTzFHZ3MycQ==","email":"mohsin.aejaz.ahmad.khan@kyndryl.com"}}}'
sshKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDiZK/Vg5LFL+ntPLxdNgBBpjLUYl1H7wzjdAlPT3au00I0WRyKmNTicr1pbo6+6deHFiGO7SsoWFkI2eVyJ+bncl0Ew2aUPE9PRIAGdWMklFI3yk2AHY5T89QlOGa67N3ZaxVjzP4qoXglcfehzuYK7Z2BMmUbYsMFch+3Oa7NrMgSFwNAIE5kkIzio4tEXdRSaANUjGdJSry4gOMo+82DyWoJzNPnRz/6SPuhLtalqE51rdOeUQ93cUgRzxSMFfmZjTZw6BYXvWhGHoQ//4j2fAhnJfdKmdasgDi6NwUYbDihG8ODjWinmyxHR8wGazbqZZP1i707ljF5Oale80sPluMxPQXS81tSbnfsr4aU334bZ0V6wC/XQxW1PRvUZXXjjQIx6xM6T2BRAxfG+MT8wf84ZN2hdg6Pm7p6SmOjY9glC+6vQZzo32pjgjU/GAtjb8rr19KJIfiDcjOObl/wAuf5xPQ7ZBd+35km8ar+7WBewkDCiGy6KVMRyHBiNdM= root@utility.cloud.lab"
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIDlzCCAn+gAwIBAgIUBqxTKvhGv2+yg4IZjPRSzoLEdK8wDQYJKoZIhvcNAQEL
  BQAwazELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xGjAYBgNVBAMMEXV0
  aWxpdHkuY2xvdWQubGFiMB4XDTI0MDkzMDE2MjIwN1oXDTI1MDkyMTE2MjIwN1ow
  GjEYMBYGA1UEAwwPcXVheS1lbnRlcnByaXNlMIIBIjANBgkqhkiG9w0BAQEFAAOC
  AQ8AMIIBCgKCAQEA3/pezyr3YjS9CK5+aq/Ap5mrE9qjziSfWzrxieyczlthZf8h
  HQNzHWnkF9f1c/6+5ESl4WNjMnBL1Oryu/ZqOlOH9KkqJJulrMlrGn8eWcXkKgKB
  t/VVvdKwNWsXLz1+d90euVGEEMkcjthM8F18XZr51FbCiY6oxIpZTxgznODAN3Vq
  jWjBEXAyOopyBSjT7iH96oY97kN7DZxiUl2pZsbr0v2C8dnKr1M9fnqi5D0I7ZgB
  IwU7OnCkr/awqBkDr5emf+FA0d6Ms2wKThFVmbJH4hpmd3nu/VUOiPrdqp0l8S5v
  nkj/frNaQFWG3njr7UEpVPnSwzTWxZaE8iUk+wIDAQABo4GDMIGAMAsGA1UdDwQE
  AwIC5DATBgNVHSUEDDAKBggrBgEFBQcDATAcBgNVHREEFTATghF1dGlsaXR5LmNs
  b3VkLmxhYjAdBgNVHQ4EFgQUuKLVezQjFPM8xUOzfT5AfC4XYUYwHwYDVR0jBBgw
  FoAU/SsZ4yKtRlOoLY3R+qlNZc1652IwDQYJKoZIhvcNAQELBQADggEBADh3bO8I
  6h6aCAfPBJSlv/ppPgBaQ+DkkyF9GpfklGphfJCFtJewCDgNJocOAWaKx5HYBX2v
  RqQxhlhrubIXfOdAW+kasazvMwCnBH2mOuwNMgV5fk96TnysAPZg16b61MXHmcOb
  nWcdUR1PLPeozQ6LgXfkBc/tngxeTwM0sjkLyTeAmR8tFgO0uCrrwpLLz/kgG3Wu
  tJ2F8vWpXghIlORN/Cmf6TgpKedYKtfQVw2Psl+zkRA2SXlTw7e0KSaTTPWbOqG6
  lV5SRj9JF4rvvvLshDX4JJ3RuWTGLdUKPFp6zzSwNrI234EYGSb7a3O3QVDx9DX6
  VNDh6xpSgqm8+8M=
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIID2TCCAsGgAwIBAgIUcoo5+V1P9/NX9P5wevZqkyWyT+AwDQYJKoZIhvcNAQEL
  BQAwazELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xGjAYBgNVBAMMEXV0
  aWxpdHkuY2xvdWQubGFiMB4XDTI0MDkzMDE2MjIwM1oXDTI3MDcyMTE2MjIwM1ow
  azELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9yazEN
  MAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xGjAYBgNVBAMMEXV0aWxp
  dHkuY2xvdWQubGFiMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArBK/
  bYJXKiPv00rkxGIV86t3iq2ZyQUXFHElki2XfkviVwwELOh4Qo5qfdoBDdy4Qrwv
  2X9bOhxTu5Dh3ZtsMdsx5smqDQg8yLBA9p2MUMWYduZyw9seUEBZr4Fs4tR9BJZN
  XgAszwlWERSnCl7TQW6ZX/6y828O333jN4mvQrmF51V6e4eciaBPz/pfgzkgFS+W
  OSr7Wynvpyaxq72PbSiqxwTSaZdRVnhxzMFWh+u5vKBPuCEWyF9Hv5w9rStVYeck
  3YXhsnbVgok/oFvRJgZkmFkM4oGSyeOi/bkIksdel+m41q6691F9ey+vNyeT20/o
  OXLmLXIkaw+Q0lKwYQIDAQABo3UwczALBgNVHQ8EBAMCAuQwEwYDVR0lBAwwCgYI
  KwYBBQUHAwEwHAYDVR0RBBUwE4IRdXRpbGl0eS5jbG91ZC5sYWIwEgYDVR0TAQH/
  BAgwBgEB/wIBATAdBgNVHQ4EFgQU/SsZ4yKtRlOoLY3R+qlNZc1652IwDQYJKoZI
  hvcNAQELBQADggEBAGuDC5VFjxehTHl7PRCntkH6wLUo5HEaoT2sRKFNUVblYMTi
  GJmQrA99nyJFmNQB+Ebo6vUJyKSplJQjiuOFyiQlFVqiQzMaCnjocbWRFECs7SON
  XNLkwewZQl3JP87V4WUHyCidBPQeEO1ekMm9SD3Hv3zBWKsVsatNy0vN8KzlRU3I
  uxMfmwYMUhO6aST6/8ZcVuAdfLv2c5gEzxZgdFuZL/LPuWtUtdYFsVd05RUKYlv/
  +v9wc/eFRKpzMSoUjRRMJY66CpISJKnrEkrnMN3KnBXcgB2/5GOnI47Dfz0kUVW4
  yGPEJltv1upThfuHc4hAiONnmdV9IbtyOWTZUr4=
  -----END CERTIFICATE-----