apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-ops
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  lables:
    app.kubernetes.io/instance: app-of-apps
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Project contains applications related to cluster operations
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/glaceroy/gitops-cluster-control.git