apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops-operator
  annotations:
    openshift.io/node-selector : node-role.kubernetes.io/infra=
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-gitops-operator.v1.12.0
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ''