apiVersion: v1
kind: Namespace
metadata:
  name: openshift-pipelines-operator
#  annotations:
#    openshift.io/node-selector : node-role.kubernetes.io/infra=
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: pipelines-operator
  namespace: openshift-pipelines-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: pipelines-operator
  namespace: openshift-pipelines-operator
spec:
  channel: pipelines-1.15
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-pipelines-operator-rh.v1.15.1
#  config:
#    nodeSelector:
#      node-role.kubernetes.io/infra: ''