apiVersion: v1
kind: Namespace
metadata:
  name: openshift-pipelines-operator
#  annotations:
#    openshift.io/node-selector : node-role.kubernetes.io/infra=
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-pipelines-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: pipelines-operator
  namespace: openshift-pipelines-operator
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-pipelines-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
#  config:
#    nodeSelector:
#      node-role.kubernetes.io/infra: ''