kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: utility.cloud.lab:8443/mirror/oc-mirror-metadata-rh-ops-4-14 # Local mirror registry URL
    skipTLS: false
mirror:                      # This parameter will be useful when updating the cluster in disconnected setup with OSUS operator
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14 # Version of the operators catalog to be mirrored. 
    targetName: 'redhat-operator-index'
    targetTag: 'v4.14.6'
    packages:
    - name: kiali-ossm
      channels:
      - name: stable
        minVersion: '1.73.8'
    - name: openshift-gitops-operator
      channels:
      - name: latest
        minVersion: '1.12.0'
    - name: openshift-pipelines-operator-rh
      channels:
      - name: pipelines-1.15
        minVersion: '1.15.1'
    - name: servicemeshoperator
      channels:
      - name: stable
        minVersion: '2.5.2-0'
  additionalImages:
  - name: registry.redhat.io/openshift-service-mesh/istio-must-gather-rhel8:2.6.0-7
  helm: {}