kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: utility.cloud.lab:8443/mirror/oc-mirror-metadata-rh-ops-4-16 # Local mirror registry URL
    skipTLS: false
mirror:                      # This parameter will be useful when updating the cluster in disconnected setup with OSUS operator
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16 # Version of the operators catalog to be mirrored. 
    targetName: 'redhat-operator-index'
    targetTag: 'v4.16..1'
    packages:
    - name: cluster-logging
      channels:
      - name: stable
        minVersion: '5.9.4'
    - name: loki-operator
      channels:
      - name: stable
        minVersion: '5.9.4'
    - name: kiali-ossm
      channels:
      - name: stable
        minVersion: '1.73.10'
    - name: local-storage-operator
      channels:
      - name: stable
        minVersion: '4.16.0-202407190036'
    - name: openshift-gitops-operator
      channels:
      - name: latest
        minVersion: '1.14.0'
    - name: openshift-pipelines-operator-rh
      channels:
      - name: latest
        minVersion: '1.15.1'
      - name: pipelines-1.15
        minVersion: '1.15.1'
    - name: servicemeshoperator
      channels:
      - name: stable
        minVersion: '2.5.2-0'
    - name: redhat-oadp-operator
      channels:
      - name: stable-1.4
        minVersion: '1.4.0'
    - name: odf-operator
      channels:
      - name: stable-4.16
        minVersion: '4.16.0-rhodf'
  additionalImages:
  - name: registry.redhat.io/openshift-service-mesh/istio-must-gather-rhel8:2.6.0-7
  helm: {}