apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: app-ingress-01
  namespace: openshift-ingress-operator
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  domain: app-ingress-01.ocp.cloud.lab
  endpointPublishingStrategy:
    nodePort:
      protocol: PROXY
    type: NodePortService
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  idleConnectionTerminationPolicy: Deferred
  logging:
    access:
      destination:
        type: Container
      httpCaptureHeaders: {}
      logEmptyRequests: Log
  namespaceSelector:
    matchLabels:
      ingress-shard: app-ingress-01
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra-proxy: ""
  replicas: 2
  tuningOptions:
    reloadInterval: 0s
  unsupportedConfigOverrides: null
