apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  defaultCertificate:
    name: default-ingress
  endpointPublishingStrategy:
    hostNetwork:
      httpPort: 80
      httpsPort: 443
      protocol: TCP
      statsPort: 1936
    type: HostNetwork
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  logging:
    access:
      destination:
        type: Container
      httpCaptureHeaders: {}
      logEmptyRequests: Log
  namespaceSelector:
    matchExpressions:
    - key: ingress-shard
      operator: NotIn
      values:
      - app-ingress-01
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra-proxy: ""
  replicas: 2
  tuningOptions:
    reloadInterval: 0s
  unsupportedConfigOverrides: null
