apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
#  annotations:
#    openshift.io/node-selector : node-role.kubernetes.io/infra=
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-kiali
#  annotations:
#    openshift.io/node-selector : node-role.kubernetes.io/infra=
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-servicemesh
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kiali-operator
  namespace: openshift-kiali
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: servicemesh-operator
  namespace: openshift-servicemesh
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/servicemesh-operator.openshift-operators: ""
  name: kiali-ossm
  namespace: openshift-kiali
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kiali-ossm
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
#  config:
#    nodeSelector:
#      node-role.kubernetes.io/infra: ''
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/servicemeshoperator.openshift-operators: ""
  name: servicemeshoperator
  namespace: openshift-servicemesh
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace 
  startingCSV: servicemeshoperator.v2.5.2
#  config:
#    nodeSelector:
#      node-role.kubernetes.io/infra: ''