apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  creationTimestamp: "2025-03-12T16:45:39Z"
  finalizers:
  - maistra.io/istio-operator
  generation: 1
  name: app-mesh-01
  namespace: istio-system
  resourceVersion: "3266705"
  uid: bdcfd694-2498-4f1b-b5b8-591907b71ed7
spec:
  addons:
    grafana:
      enabled: false
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: false
  gateways:
    additionalEgress:
      eg0001:
        enabled: true
        namespace: lbg-eng-test-001-lab-cloud
        runtime:
          container:
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 128Mi
          deployment:
            autoScaling:
              enabled: false
            replicas: 1
          pod:
            metadata:
              annotations:
                CMDB_AppID: AL12345
    additionalIngress:
      ig0001:
        enabled: true
        namespace: lbg-eng-test-001-lab-cloud
        runtime:
          container:
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 128Mi
          deployment:
            autoScaling:
              enabled: false
            replicas: 1
          pod:
            metadata:
              annotations:
                CMDB_AppID: AL12345
    openshiftRoute:
      enabled: false
  mode: MultiTenant
  policy:
    type: Istiod
  profiles:
  - default
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: None
  version: v2.5
