apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  name: cluster
spec:
  httpProxy: http://utility.cloud.lab:3128
  httpsProxy: https://utility.cloud.lab:3129
  noProxy: example.com
  readinessEndpoints:
  - http://www.google.com 
  - https://www.google.com
  trustedCA:
    name: user-ca-bundle