apiVersion: v1
data:
  ca-bundle.crt: | 
    -----BEGIN CERTIFICATE-----
    MIIFvzCCA6egAwIBAgIUNaNOjgCqkXcTaydUs3L+VBKNUZUwDQYJKoZIhvcNAQEL
    BQAwbzELMAkGA1UEBhMCVUsxETAPBgNVBAgMCENoZXNoaXJlMREwDwYDVQQHDAhD
    aGVzaGlyZTEQMA4GA1UECgwHSG9tZWxhYjEOMAwGA1UECwwFQ2xvdWQxGDAWBgNV
    BAMMD0hvbWVsYWIgUm9vdCBDQTAeFw0yNDEwMDgxMjA2NTdaFw0zNDEwMDYxMjA2
    NTdaMG8xCzAJBgNVBAYTAlVLMREwDwYDVQQIDAhDaGVzaGlyZTERMA8GA1UEBwwI
    Q2hlc2hpcmUxEDAOBgNVBAoMB0hvbWVsYWIxDjAMBgNVBAsMBUNsb3VkMRgwFgYD
    VQQDDA9Ib21lbGFiIFJvb3QgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
    AoICAQC1AMOSJAqFkChdRDK4PEzBcx2/5GH841F/dgQOdBLOIB4Wws+fiZAyTORR
    WYziaNOLat5SxUz8cLZ3naZW2O/rbpPO9mlyuc/4q+TEE4pDnD8+eB4dUyb1u0rx
    pJVweWDsDGL8y4afS3vhBmCWdX+xkwkj6qtSDbWsGWOHHmXNoykbkMoIOYlfJns3
    dlaZRb6ZgphgkR3luVD3mnDxE1o285S68GOIBM5XdfmxsGog9M8qQwB0zS2SHvlY
    hqSWRG+ROZvk2VLdvq+LLR0yd0D3SRYz9Cun0cOkc8i/w1nNVKc8OXMgmepCEKwL
    boudolTSRFzc1IzaXh3tv3dwZ/iWf4VCE7mIfcKGtMYi0zefG/lmlCYtIoc/WYcQ
    kEi7fGchu8pzyzDVPzEPnyUAl0AIm0PezwXsuFH4wxOnxHGwJUyNPl4G6xT6rpT0
    xN8afhYtE5KPP7U6MR/maueNYvsL3vMO3zE8bLey5H9d3OX68y3nkKbTjKToY39j
    5ALaIxfctvWUVsmbWYuwbpjWoud+/UrfBuJCeWN3WYmFtQk1q9y5+WiCDTdFoLNT
    mSnYF3FTMRuTX3yJCWWRstDKYpL/NjuOjDt+o5uXhXqS+amTHCq7QwY1ME1wvOw7
    r3YttM4imD0E2pptU8uodlbftNlJ5v0f5bReeSzO99XWU5h/8wIDAQABo1MwUTAd
    BgNVHQ4EFgQUMYiL/6dVJipoRZmuGzFCntGFf2gwHwYDVR0jBBgwFoAUMYiL/6dV
    JipoRZmuGzFCntGFf2gwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
    AgEAg6+b/wWtirviMQ1YNvf35VIxAlFII0BB+CZpHIvhOCS5pME9kbYw643HWz3Y
    aTZvtqHQN5MLPMjcUK630gxjKHAzB3DpGKb8Y39Qt4QG4CxiPt/1SXoDfwQoRz5V
    DRnOy6445xpO7vER8MIKtyFKtrYg89l3SKlZqyzZpsTyctnqmRKo7gRrxo7V1MjF
    kenAtF0Hv84avTUSPO/o1zt0BFgVJVjbLH2iQI9d2+1O1f/uYUtvgM4830DlNR7I
    HIuKi5pgtnttsWqWbSLZKV/IRhfmiWdoDQTpVeEYc/VaoKQkNxDf6WYCYF6Qk1Ju
    GOpae+YSShd7RtuAzC5PqiJhdl+EOSQMCR6M03XzfQcQ1ihwyiLnel5k36WNZyTJ
    ztEwIboks8jn4gEpG8XRl9QlQDBBanDzTGej19bZ4TLMAhLQQs7gvF057NbclmH0
    LJ+SKgdO+buQaHvRI7eSoN2+NMgsjKJMFyOFHi4mSxBBEg+FGNiwdw64OYFi/bw8
    civXukG00tk5JVTe0MJwNSJUqeX3pT0Y0mswuoUoVnMvGRgVZ4DeJ6IFxsDk5+U/
    C0BRbjxJZs5Z6HfqcJR1D586wJlon92sNkr9AS55vnpeM3gFOcLWvEDt6TOjTzzv
    3qO897+2F76IWfU4CGsnUFwUTkentykb2lPIXiGlg++N6Zc=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: user-ca-bundle
  namespace: openshift-config