apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: operator-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - utility.cloud.lab:8443/openshift-gitops-1
    source: registry.redhat.io/openshift-gitops-1
  - mirrors:
    - utility.cloud.lab:8443/openshift-service-mesh
    source: registry.redhat.io/openshift-service-mesh
  - mirrors:
    - utility.cloud.lab:8443/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - utility.cloud.lab:8443/source-to-image
    source: registry.redhat.io/source-to-image
  - mirrors:
    - utility.cloud.lab:8443/ubi8
    source: registry.redhat.io/ubi8
  - mirrors:
    - utility.cloud.lab:8443/rh-sso-7
    source: registry.redhat.io/rh-sso-7
  - mirrors:
    - utility.cloud.lab:8443/openshift-pipelines
    source: registry.redhat.io/openshift-pipelines
  - mirrors:
    - utility.cloud.lab:8443/rhel8
    source: registry.redhat.io/rhel8
  - mirrors:
    - utility.cloud.lab:8443/rhel9
    source: registry.redhat.io/rhel9
  - mirrors:
    - utility.cloud.lab:8443/openshift-serverless-1
    source: registry.redhat.io/openshift-serverless-1
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: release-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - utility.cloud.lab:8443/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - utility.cloud.lab:8443/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release