apiVersion: v1
kind: Namespace
metadata:
  name: vault-secrets-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: vault-secrets-operator
  source: cs-certified-operator-index
  sourceNamespace: openshift-marketplace

