---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: itms-generic-0
spec:
  imageTagMirrors:
  - mirrors:
    - registry.cloud.lab:8443/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - registry.cloud.lab:8443/ubi8
    source: registry.redhat.io/ubi8
  - mirrors:
    - registry.cloud.lab:8443/ubi9
    source: registry.redhat.io/ubi9
  - mirrors:
    - registry.cloud.lab:8443/rhel8
    source: registry.redhat.io/rhel8
  - mirrors:
    - registry.cloud.lab:8443/rhel9
    source: registry.redhat.io/rhel9
status: {}
---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: itms-release-0
spec:
  imageTagMirrors:
  - mirrors:
    - registry.cloud.lab:8443/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
status: {}
