---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: itms-release-0
spec:
  imageTagMirrors:
  - mirrors:
    - registry.cloud.lab:8443/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
status: {}
